INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (1,'Root','Root',NULL,1,50,0);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (2,'pages','Pages','Pages in website',2,25,1);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (3,'products','Products','Product list',26,49,1);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (4,'Home','Home',NULL,3,24,2);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (5,'About','About us',NULL,4,9,3);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (6,'Contact','Contact us',NULL,5,6,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (7,'Events','Our events',NULL,7,8,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (8,'Service','Service',NULL,10,21,3);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (9,'Products','Products',NULL,11,18,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (10,'Search','Search',NULL,12,13,5);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (11,'Reviews','Reviews',NULL,14,15,5);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (12,'FAQ','FAQ',NULL,19,20,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (13,'Order','Shoppingcart',NULL,22,23,3);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (14,'Furniture','Furniture',NULL,27,46,2);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (15,'Office','Office suplies',NULL,47,48,2);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (16,'Living','Living',NULL,28,33,3);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (17,'Kitchen','Kitchen',NULL,34,35,3);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (18,'Bedroom','Bedroom',NULL,36,45,3);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (19,'Chairs','Chairs',NULL,29,30,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (20,'Tables','Tables',NULL,31,32,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (21,'Chairs','Chairs',NULL,37,38,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (22,'Tables','Tables',NULL,39,40,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (23,'Beds','Beds',NULL,41,42,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (24,'Closets','Closets',NULL,43,44,4);
INSERT INTO `trees` (`tree_id`,`name`,`label`,`description`,`lft`,`rht`,`lvl`) VALUES (25,'Furniture','Furniture',NULL,16,17,5);
