TRUNCATE TABLE trees;
\. create_procedures.sql
CALL tree_add_root();
CALL tree_add_node(1,'pages','Pages','Pages in website');
CALL tree_add_node(1,'products','Products','Product list');
CALL tree_add_node(2,'Home','Home',NULL);
CALL tree_add_node(4,'About','About us',NULL);
CALL tree_add_node(5,'Contact','Contact us',NULL);
CALL tree_add_node(5,'Events','Our events',NULL);
CALL tree_add_node(4,'Service',NULL,NULL);
CALL tree_add_node(8,'Products','Products',NULL);
CALL tree_add_node(9,'Search','Search',NULL);
CALL tree_add_node(9,'Reviews','Reviews',NULL);
CALL tree_add_node(8,'FAQ','FAQ',NULL);
CALL tree_add_node(4,'Order','Shoppingcart',NULL);
CALL tree_add_node(3,'Furniture',NULL,NULL);
CALL tree_add_node(3,'Office','Office suplies',NULL);
CALL tree_add_node(14,'Living',NULL,NULL);
CALL tree_add_node(14,'Kitchen',NULL,NULL);
CALL tree_add_node(14,'Bedroom',NULL,NULL);
CALL tree_add_node(16,'Chairs',NULL,NULL);
CALL tree_add_node(16,'Tables',NULL,NULL);
CALL tree_add_node(18,'Chairs',NULL,NULL);
CALL tree_add_node(18,'Tables',NULL,NULL);
CALL tree_add_node(18,'Beds',NULL,NULL);
CALL tree_add_node(18,'Closets',NULL,NULL);
-- CALL tree_add_node(18,'beds',NULL,NULL);
CALL tree_add_node(9,'Furniture',NULL,NULL);
-- CALL tree_update_node(25,'Beds','other beds');
-- CALL tree_get_branch_by_name('Products','Furniture',1,'--');
-- CALL tree_get_branch(14,2,'--');
-- CALL tree_get_parents(23,'--');
-- CALL tree_swap_leafs(23,21);
-- CALL tree_change_position(21,22,'after');
-- CALL tree_get_all('--');
-- CALL tree_del(14);
CALL tree_get_all(NULL,'--');
-- SELECT * FROM trees ORDER BY lft ASC;
